"""add_strategies_table

Revision ID: 1f2bce260ec4
Revises: 84b229ef41d5
Create Date: 2025-11-21 10:44:11.510617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2bce260ec4'
down_revision = '84b229ef41d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('strategy_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='策略ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('strategy_type', sa.String(length=20), nullable=False, comment='策略类型: buy/sell/hold'),
    sa.Column('trigger_price', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='触发价格'),
    sa.Column('target_quantity', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='目标数量'),
    sa.Column('reason', sa.Text(), nullable=True, comment='策略原因/理由'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/completed/cancelled'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='优先级: urgent/high/normal/low'),
    sa.Column('is_stop_loss', sa.Boolean(), nullable=True, comment='是否止损策略'),
    sa.Column('is_take_profit', sa.Boolean(), nullable=True, comment='是否止盈策略'),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='执行时间'),
    sa.Column('executed_price', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='实际执行价格'),
    sa.Column('executed_quantity', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='实际执行数量'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_index('idx_strategies_status', 'strategies', ['status'], unique=False)
    op.create_index('idx_strategies_symbol', 'strategies', ['symbol'], unique=False)
    op.create_index('idx_strategies_user_id', 'strategies', ['user_id'], unique=False)
    op.create_index('idx_strategies_user_symbol', 'strategies', ['user_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_index('idx_strategies_user_symbol', table_name='strategies')
    op.drop_index('idx_strategies_user_id', table_name='strategies')
    op.drop_index('idx_strategies_symbol', table_name='strategies')
    op.drop_index('idx_strategies_status', table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
