"""Initial schema with all models

Revision ID: 84b229ef41d5
Revises: 
Create Date: 2025-11-17 23:14:37.962967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84b229ef41d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='账户ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('account_name', sa.String(length=100), nullable=False, comment='账户名称'),
    sa.Column('account_number', sa.String(length=50), nullable=False, comment='账户号码'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场类型: A股/港股/美股'),
    sa.Column('broker', sa.String(length=100), nullable=False, comment='券商名称'),
    sa.Column('total_value', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='总资产'),
    sa.Column('available_cash', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='可用资金'),
    sa.Column('invested_value', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='持仓市值'),
    sa.Column('today_profit', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='今日盈亏'),
    sa.Column('today_profit_rate', sa.NUMERIC(precision=10, scale=4), nullable=True, comment='今日盈亏率 (%)'),
    sa.Column('total_profit', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='累计盈亏'),
    sa.Column('total_profit_rate', sa.NUMERIC(precision=10, scale=4), nullable=True, comment='累计盈亏率 (%)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='账户状态: active/inactive/closed'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index('idx_accounts_user_market', 'accounts', ['user_id', 'market'], unique=False)
    op.create_index('idx_accounts_user_status', 'accounts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('conversation_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('context_symbol', sa.String(length=20), nullable=True, comment='上下文股票代码'),
    sa.Column('context_type', sa.String(length=50), nullable=True, comment='上下文类型'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='消息列表 [{role, content, timestamp}]'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='消耗Token总数'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_ai_conversations_context_symbol', 'ai_conversations', ['context_symbol'], unique=False)
    op.create_index('idx_ai_conversations_user', 'ai_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('decision_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='决策ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('analysis_type', sa.String(length=50), nullable=False, comment='分析类型: daily/single/portfolio'),
    sa.Column('ai_score', sa.JSON(), nullable=True, comment='AI评分详情 {fundamental_score, technical_score, valuation_score, overall_score}'),
    sa.Column('ai_suggestion', sa.Text(), nullable=False, comment='AI建议'),
    sa.Column('ai_strategy', sa.JSON(), nullable=True, comment='AI策略 {target_price, recommended_position, risk_level, holding_period, stop_loss_price}'),
    sa.Column('ai_reasons', postgresql.ARRAY(sa.Text()), nullable=True, comment='AI理由列表'),
    sa.Column('confidence_level', sa.NUMERIC(precision=10, scale=4), nullable=True, comment='置信度 (0-100)'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('idx_ai_decisions_analysis_type', 'ai_decisions', ['analysis_type'], unique=False)
    op.create_index('idx_ai_decisions_created_date', 'ai_decisions', ['created_at'], unique=False)
    op.create_index('idx_ai_decisions_user_symbol', 'ai_decisions', ['user_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_ai_decisions_symbol'), 'ai_decisions', ['symbol'], unique=False)
    op.create_index(op.f('ix_ai_decisions_user_id'), 'ai_decisions', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='事件ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='事件标题'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='事件类别: policy/company/market/industry'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='事件类型'),
    sa.Column('symbol', sa.String(length=20), nullable=True, comment='关联股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='事件内容'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='来源链接'),
    sa.Column('event_date', sa.TIMESTAMP(timezone=True), nullable=False, comment='事件日期'),
    sa.Column('impact_level', sa.Integer(), nullable=True, comment='影响等级 1-5'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI分析'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_events_category_date', 'events', ['category', 'event_date'], unique=False)
    op.create_index('idx_events_symbol', 'events', ['symbol'], unique=False)
    op.create_index('idx_events_user_category', 'events', ['user_id', 'category'], unique=False)
    op.create_index('idx_events_user_date', 'events', ['user_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_symbol'), 'events', ['symbol'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('holdings',
    sa.Column('holding_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='持仓ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='账户ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('quantity', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='持仓数量'),
    sa.Column('available_quantity', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='可用数量'),
    sa.Column('avg_cost', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='持仓成本'),
    sa.Column('current_price', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='当前价格'),
    sa.Column('market_value', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='市值'),
    sa.Column('profit', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='盈亏金额'),
    sa.Column('profit_rate', sa.NUMERIC(precision=10, scale=4), nullable=True, comment='盈亏率 (%)'),
    sa.Column('today_profit', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='今日盈亏'),
    sa.Column('today_profit_rate', sa.NUMERIC(precision=10, scale=4), nullable=True, comment='今日盈亏率 (%)'),
    sa.Column('position_ratio', sa.NUMERIC(precision=10, scale=4), nullable=True, comment='仓位占比 (%)'),
    sa.Column('first_buy_date', sa.TIMESTAMP(timezone=True), nullable=True, comment='首次买入日期'),
    sa.Column('last_update_time', sa.TIMESTAMP(timezone=True), nullable=True, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_index('idx_holdings_account_symbol', 'holdings', ['account_id', 'symbol'], unique=False)
    op.create_index('idx_holdings_symbol', 'holdings', ['symbol'], unique=False)
    op.create_index('idx_holdings_user_account', 'holdings', ['user_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_holdings_account_id'), 'holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('stocks',
    sa.Column('stock_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='股票ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场类型: A股/港股/美股'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='所属行业'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='所属板块'),
    sa.Column('list_date', sa.Date(), nullable=True, comment='上市日期'),
    sa.Column('pinyin', sa.String(length=50), nullable=True, comment='拼音首字母'),
    sa.Column('is_delisted', sa.Boolean(), nullable=False, comment='是否退市'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_index('idx_stocks_market', 'stocks', ['market'], unique=False)
    op.create_index('idx_stocks_name', 'stocks', ['name'], unique=False)
    op.create_index(op.f('ix_stocks_pinyin'), 'stocks', ['pinyin'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('trades',
    sa.Column('trade_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='交易ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='账户ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('trade_type', sa.String(length=20), nullable=False, comment='交易类型: buy/sell'),
    sa.Column('quantity', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='交易数量'),
    sa.Column('price', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='交易价格'),
    sa.Column('total_amount', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='交易金额'),
    sa.Column('commission', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='手续费'),
    sa.Column('stamp_duty', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='印花税'),
    sa.Column('transfer_fee', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='过户费'),
    sa.Column('net_amount', sa.NUMERIC(precision=20, scale=8), nullable=False, comment='净金额'),
    sa.Column('trade_date', sa.TIMESTAMP(timezone=True), nullable=False, comment='交易日期'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('idx_trades_account_symbol', 'trades', ['account_id', 'symbol'], unique=False)
    op.create_index('idx_trades_symbol_date', 'trades', ['symbol', 'trade_date'], unique=False)
    op.create_index('idx_trades_trade_date', 'trades', ['trade_date'], unique=False)
    op.create_index('idx_trades_user_account', 'trades', ['user_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_date'), 'trades', ['trade_date'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('user_stock_reviews',
    sa.Column('review_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='评价ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='评分 1-5星'),
    sa.Column('bullish_reasons', postgresql.ARRAY(sa.Text()), nullable=True, comment='看好原因列表'),
    sa.Column('bearish_reasons', postgresql.ARRAY(sa.Text()), nullable=True, comment='风险原因列表'),
    sa.Column('holding_logic', sa.Text(), nullable=True, comment='持有逻辑'),
    sa.Column('target_price', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='目标价'),
    sa.Column('stop_loss_price', sa.NUMERIC(precision=20, scale=8), nullable=True, comment='止损价'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('idx_reviews_rating', 'user_stock_reviews', ['rating'], unique=False)
    op.create_index('idx_reviews_user_symbol', 'user_stock_reviews', ['user_id', 'symbol'], unique=True)
    op.create_index(op.f('ix_user_stock_reviews_symbol'), 'user_stock_reviews', ['symbol'], unique=False)
    op.create_index(op.f('ix_user_stock_reviews_user_id'), 'user_stock_reviews', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_stock_reviews_user_id'), table_name='user_stock_reviews')
    op.drop_index(op.f('ix_user_stock_reviews_symbol'), table_name='user_stock_reviews')
    op.drop_index('idx_reviews_user_symbol', table_name='user_stock_reviews')
    op.drop_index('idx_reviews_rating', table_name='user_stock_reviews')
    op.drop_table('user_stock_reviews')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_trade_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_index('idx_trades_user_account', table_name='trades')
    op.drop_index('idx_trades_trade_date', table_name='trades')
    op.drop_index('idx_trades_symbol_date', table_name='trades')
    op.drop_index('idx_trades_account_symbol', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_pinyin'), table_name='stocks')
    op.drop_index('idx_stocks_name', table_name='stocks')
    op.drop_index('idx_stocks_market', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_account_id'), table_name='holdings')
    op.drop_index('idx_holdings_user_account', table_name='holdings')
    op.drop_index('idx_holdings_symbol', table_name='holdings')
    op.drop_index('idx_holdings_account_symbol', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_symbol'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_index('idx_events_user_date', table_name='events')
    op.drop_index('idx_events_user_category', table_name='events')
    op.drop_index('idx_events_symbol', table_name='events')
    op.drop_index('idx_events_category_date', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_ai_decisions_user_id'), table_name='ai_decisions')
    op.drop_index(op.f('ix_ai_decisions_symbol'), table_name='ai_decisions')
    op.drop_index('idx_ai_decisions_user_symbol', table_name='ai_decisions')
    op.drop_index('idx_ai_decisions_created_date', table_name='ai_decisions')
    op.drop_index('idx_ai_decisions_analysis_type', table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_index('idx_ai_conversations_user', table_name='ai_conversations')
    op.drop_index('idx_ai_conversations_context_symbol', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index('idx_accounts_user_status', table_name='accounts')
    op.drop_index('idx_accounts_user_market', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
